### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Ekwav** [Ekwav/UF_OAUTH2-SERVER#1]
Things that are left to do:
- [ ]  Implement a page for admins to add and update Apps
- [ ]  Add a slim extension, to be able to do `->add('api');` 
- [ ]  Change the authorization page to use ajax
